#!/usr/bin/env php
<?php
/**
 * File containing the CjwMultiSiteBundle console logic
 *
 * @copyright Copyright (C) 2007-2014 CJW Network - Coolscreen.de, JAC Systeme GmbH, Webmanufaktur. All rights reserved.
 * @license http://ez.no/licenses/gnu_gpl GNU GPL v2
 * @version //autogentag//
 * @filesource
 *
 */
// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

// load console from CjwMultiSiteBundle
require_once __DIR__ . '/../vendor/cjw-network/multisite-bundle/app/include_console.php';